library(knitr)
library(plyr)
library(dplyr)
library(readr)
library(rvest)
library(gsubfn)
library(ggplot2)
library(reshape2)
library(shiny)
library(XML)
library(tidyr)
library(ggthemes)
library(extrafont)
library(scales)
require(rworldmap)
require(ggplot2)
library(maptools)
library(rgdal)
library(ggmap)
library(ggvis)
library(rgeos)
library(RColorBrewer)
library(rvest)
library(geojsonio)
library(spdplyr)
library(rmapshaper)
library(leaflet)
library(rmarkdown)
library(httpuv)
library(caTools)

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding = "UTF-8")

